language: objective-c
osx_image: xcode8.1
cache:
    - bundler
rvm:
    - 2.2
before_install:
    - gem install fastlane
    - gem install slather
    - brew update
    - brew install swiftlint
script: 
    - swiftlint
    - travis_retry fastlane test
after_success:
    - slather coverage -x --scheme SentrySwift-iOS --ignore "*ViewController.swift" SentrySwift.xcodeproj
    - bash <(curl -s https://codecov.io/bash) -f cobertura.xml