language: objective-c
osx_image: xcode8.3
cache:
    - bundler
rvm:
    - 2.2
script:
    - .travis/run.sh
after_success:
    - if [ "$LANE" = "test" ]; then bash <(curl -s https://codecov.io/bash) -J '^Sentry$'; elif [ "$LANE" = "test_swift" ]; then bash <(curl -s https://codecov.io/bash) -J '^SentrySwift$'; fi
env:
    matrix:
        - LANE=lint
        - LANE=test
        - LANE=test_swift
        - LANE=do_cocoapods KSCRASH=true PLATFORM=ios
notifications:
  email: false
