language: objective-c
osx_image: xcode8.3
cache:
    - bundler
rvm:
    - 2.2
script:
    - travis_retry .travis/run.sh
after_success:
    - if [ "$LANE" = "test" ]; then slather coverage --scheme Sentry && bash <(curl -s https://codecov.io/bash) -f cobertura.xml; fi
env:
    matrix:
        - LANE=lint
        - LANE=test
notifications:
  email: false
