language: objective-c
osx_image: xcode8.3
cache:
    - bundler
rvm:
    - 2.2
before_install:
    - bundle install
    - brew update
    - brew outdated swiftlint || brew upgrade swiftlint
script:
    - if [ "$LANE" = "lint" ]; then fastlane $LANE; else travis_retry fastlane $LANE; fi
#after_success:
#    - if [ "$LANE" = "test_swift_3_ios" ]; then bash <(curl -s https://codecov.io/bash) -f cobertura.xml; fi
env:
    matrix:
        - LANE=lint
        - LANE=test
        - LANE=test_swift
        - LANE=do_cocoapods kscrash:true platform:ios
notifications:
  email: false
