language: objective-c
osx_image: xcode8.2
cache:
    - bundler
rvm:
    - 2.2
before_install:
    - gem install fastlane
    - gem install slather
    - brew update
    - brew outdated swiftlint || brew upgrade swiftlint
script: 
    - travis_retry fastlane $LANE
after_success:
    - if [ "$LANE" = "coverage" ]; then bash <(curl -s https://codecov.io/bash) -f cobertura.xml; fi 
matrix:
  fast_finish: true
  include:
    - env: LANE=lint
    - env: LANE=test_swift_2
    - env: LANE=test_swift_3
    - env: LANE=coverage